<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="index.php">
            <strong>MyBOX</strong>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="index.php">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="carpetas.php">Carpetas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Opción 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Opción 2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="codes/salir.php">Salir</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
